source 'http://rubygems.org'
#escolher as gems para se utilizar no projeto
gem 'cucumber'
gem 'capybara'
gem 'selenium-webdriver'
gem 'rspec'
gem 'site_prism'
gem 'faker'
gem "chromedriver-helper"
